services:
    lunchmoney-mcp:
        build:
            context: .
            dockerfile: Dockerfile
            no_cache: true
        restart: unless-stopped
        environment:
            LUNCHMONEY_API_TOKEN: ${LUNCHMONEY_API_TOKEN}
            LUNCHMONEY_ATTACHMENTS_DIR: /attachments
        volumes:
            - lunchmoney-attachments:/attachments
        networks:
            - proxied-network

networks:
    proxied-network:
        external: true

volumes:
    lunchmoney-attachments:
